theme = "github_dark_dimmed"

[editor]
default-yank-register = "+"

[keys.normal]
w='move_line_up'
s='move_line_down'
a='move_char_left'
d='move_char_right'
x='delete_selection'
del='delete_selection_noyank'
backspace='delete_selection_noyank'
S-a='move_prev_word_start'
h='select_mode'
S-d='move_next_word_start'
c='yank'
v='paste_before'
z='undo'
l='delete_selection_noyank'
f='symbol_picker'
S-w='goto_last_accessed_file'

[keys.insert]
S-tab='unindent'

[keys.select]
w='extend_line_up'
s='extend_line_down'
a='extend_char_left'
d='extend_char_right'
x='delete_selection'
del='delete_selection_noyank'
backspace='delete_selection_noyank'
l='delete_selection_noyank'
S-a='extend_prev_word_start'
h='normal_mode'
S-d='extend_next_word_start'
